### ISSUE TITLE
AttributeError: 'module' object has no attribute 'request'

### ISSUE THREAD

**Issue by ricerodriguez** [GregoryGregg/Dream_Team#3]
Issue occurs after `rosrun romi_soccer jsongwriter.py`:
```
[INFO] [1537544384.271851]: Initializing node...
[INFO] [1537544384.272416]: Initializing publisher...
[INFO] [1537544384.282779]: Done.
Traceback (most recent call last):
  File "/home/rice/Dream_Team/src/romi_soccer/bin/jsongwriter.py", line 8, in <module>
    jason = JSONGrabber()
  File "/home/rice/Dream_Team/src/romi_soccer/bin/json_grabber.py", line 24, in __init__
    with urllib.request.urlopen('http://172.16.0.1:8001/FieldData/GetData') as response:
AttributeError: 'module' object has no attribute 'request'
```

**Comment by ricerodriguez** [comment]
fixed in last push
